[package]
name = "mob"
version = "0.1.0"
authors = ["Jeremy Wright <jeremy@quiescent.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.8"
serde = "1.0.101"
serde_derive = "1.0.101"
